name: Notify

on:
  pull_request:
    types:
      - closed

jobs:
  notify:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: snow-actions/nostr@v1.7.0
        with:
          relays: ${{ vars.NOSTR_RELAYS }}
          private-key: ${{ secrets.NOSTR_PRIVATE_KEY }}
          content: |
            #nostter ${{ github.event.pull_request.title }} 
            ${{ github.event.pull_request.html_url }}
          tags: |
            - ["t", "nostter"]
  user-status:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: echo "expiration=$(date +%s --date '12 hours')" >> $GITHUB_ENV
      - uses: snow-actions/nostr@v1.7.0
        with:
          relays: ${{ vars.NOSTR_RELAYS }}
          private-key: ${{ secrets.NOSTR_PRIVATE_KEY }}
          kind: 30315
          content: |
            #nostter ${{ github.event.pull_request.title }}
          tags: |
            - ["d", "general"]
            - ["t", "nostter"]
            - ["r", "${{ github.event.pull_request.html_url }}"]
            - ["expiration", "${{ env.expiration }}"]
