name: Test

on:
  pull_request:

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm test
